### ISSUE TITLE
Context in constructor

### ISSUE THREAD

**Issue by Sozialarchiv** [archival-IIIF/presentation-builder#9]
@kerim1 Would it not be good to set `@context` in the the base constructor?

`@context`  is a required field. So for me it seems to be logical to set a default value in the constructor.

Base.ts
```typescript
 constructor(id?: string, type?: string, label?: Internationalize) {
        if (type === 'Collection' || type === 'Manifest') {
            this.setContext();
        }

        if (id) this.id = id;
        if (type) this.type = type;
        if (label) this.setLabel(label);
    }
```

With this code the @context property would appear as the very first key/value pair of the JSON representation, like it should.

See: https://iiif.io/api/presentation/3.0/#46-linked-data-context-and-extensions

**Comment by kerim1** [comment]
As mentioned in #4 in some cases you don't want a context and in other cases you want to add another couple of context JSON URLs. So, instead of hardcoding it into the constructor, it is up to the script building the manifest how to handle the context. This way we keep it flexible.

And the `@context` does not need to appear as the very first key/value pair. In fact: JSON doesn't have ordered object properties. And a JSON-LD processor would just look for the key `@context` anyway. It doesn't care where it is mentioned in the manifest.

Example 1: https://github.com/archival-IIIF/server/blob/master/src/builder/Metadata.ts#L15-L18 
In this case I build a multi-part collection referring to other collections. Only the top most collection needs the context, the child collections do not need the context.

Example 2: https://github.com/archival-IIIF/presentation-builder/blob/5645ca6c31abfee461ac25c90aba021f37f5f516/v3/AnnotationPage.ts#L14
In this case, I want to add the text granulartiy extension to the context. If the context was already set in the constructor, I wouldn't be able to change it anymore.
